spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sber1
    username: 'root'
    password: OkaRuto24!
    driverClassName: 'com.mysql.cj.jdbc.Driver'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: 'Sber2'